name: InteractiveChat-PacketEvents
version: '1.0.0-SNAPSHOT'
main: net.skullian.InteractiveChatPacketEvents
api-version: 1.13
description: Add PacketEvents support to InteractiveChat
depend: [PacketEvents]

libraries:
  - net.kyori:adventure-text-serializer-plain:4.18.0
  - - net.kyori:adventure-text-serializer-legacy:4.18.0