name: InteractiveChat-PacketEvents
version: '1.0.7'
main: net.skullian.InteractiveChatPacketEvents
api-version: 1.13
description: Add PacketEvents support to InteractiveChat
depend: [InteractiveChat, packetevents]

folia-supported: true

libraries:
  - org.incendo:cloud-paper:2.0.0-beta.10
  - org.incendo:cloud-annotations:2.0.0
  - net.bytebuddy:byte-buddy:1.17.6